config/routes.rb
Rails.application.routes.draw do

  resources :wallets

  post 'wallets/send/:id' => 'wallets#send_bitcoins', as: :send_bitcoins

end

app/models/wallet.rb
class Wallet < ActiveRecord::Base
	validates_presence_of :private_key, :public_key, :name

	validates_uniqueness_of :name

  has_many :addresses

  def self.build_secure_wallet(params)
    wallet = Wallet.new(params)

    key = Bitcoin::generate_key
    wallet.private_key = key[0]
    wallet.public_key = key[1]

    address = Address.build_new_address(wallet.public_key)
    wallet.addresses << address

    wallet
  end

  def bitcoin_key
    key = Bitcoin::Key.new(self.private_key, self.public_key)
  end

  def get_confirmed_total
    # Get all wallets and sum total
    total = 0
    self.addresses.each do |addr|
      total += addr.get_confirmed_total
    end
    total
  end

  def get_unconfirmed_total
    # Get all wallets and sum total
    total = 0
    self.addresses.each do |addr|
      total += addr.get_unconfirmed_total
    end
    total
  end

  def to_s
    self.name
  end
end

app/controllers/wallets_controller.rb
require 'bitcoin'
require 'bitcoin/bitcoin_rpc'

include Bitcoin::Builder

class WalletsController < ApplicationController
  before_action :set_wallet, only: [:show, :edit, :update, :destroy]

  # GET /wallets
  # GET /wallets.json
  def index
    @wallets = Wallet.all
  end

  # GET /wallets/1
  # GET /wallets/1.json
  def show
  end

  # GET /wallets/new
  def new
    @wallet = Wallet.new
  end

  # GET /wallets/1/edit
  def edit
  end

  # POST /wallets
  # POST /wallets.json
  def create
    @wallet = Wallet.build_secure_wallet(wallet_params)

    respond_to do |format|
      if @wallet.save
        format.html { redirect_to @wallet, notice: 'Wallet was successfully created.' }
        format.json { render :show, status: :created, location: @wallet }
      else
        format.html { render :new }
        format.json { render json: @wallet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /wallets/1
  # PATCH/PUT /wallets/1.json
  def update
    respond_to do |format|
      if @wallet.update(wallet_params)
        format.html { redirect_to @wallet, notice: 'Wallet was successfully updated.' }
        format.json { render :show, status: :ok, location: @wallet }
      else
        format.html { render :edit }
        format.json { render json: @wallet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wallets/1
  # DELETE /wallets/1.json
  def destroy
    @wallet.destroy
    respond_to do |format|
      format.html { redirect_to wallets_url, notice: 'Wallet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # Send money
  def send_bitcoins
    Bitcoin.network = :testnet3 # TODO FIX for config
    # "send_address"=>"ABC", "amount"=>"0.1", "round"=>"5"
    @wallet = Wallet.find(params[:id])

    key = @wallet.bitcoin_key

    # Work out all amounts
    @send_amount = (BigDecimal(params[:amount]) * 100000000 ).to_i # Amount to send to address
    @round_up_amount = (BigDecimal(params[:rounded_amount]) * 100000000 ).to_i - @send_amount # amount of round_up (send to donation bucket)
    @fee = (BigDecimal(params[:tx_fee]) * 100000000).to_i # Amount to leave as fee
    @total_amount = @send_amount + @fee + @round_up_amount # The amount we will be deducting from users unspent outputs

    logger.info("Total:#{@total_amount}, Sending #{@send_amount}, Rounded #{@round_amount}, Fee #{@fee}")

    # Addres
    @target_address = params[:send_address]
    
    # Get inputs to spend
    inputs = Output.find_for_amount(@total_amount, @wallet)
    
    if inputs

      @change = Output.calculate_change(inputs, @total_amount)
      

      outputs  = []
      outputs << create_output(@send_amount, @target_address)
      if @round_up_amount > 0
        outputs << create_output(@round_up_amount, "msGQ5M46fTMJ3KWg325P1RBeZPt1Jc6ZDK")
      end
      if @change > 0
        outputs << create_output(@change, @wallet.addresses.first.val)
      end

      new_tx = build_new_tx(key, inputs, outputs)
      logger.debug("NEW TX: #{new_tx.to_json}")
      logger.debug("HEX #{bin_to_hex(new_tx.to_payload)}")
      
      Transaction.create_from_tx(inputs, new_tx)
      
      begin
        # Send
        rpc = BitcoinRPC.new('http://Ulysseys:YourPassword@127.0.0.1:8332') # TODO set config
        rpc.send_raw_trans(bin_to_hex(new_tx.to_payload))

        respond_to do |format|
          format.html { redirect_to @wallet, notice: 'Bitcoins have been sent.' }
          format.json { head :no_content }
        end
        return
      rescue Bitcoin::BitcoinRPC::BitcoinRPCError
        # TODO handle the error gracefully
      end
    end

    flash[:error] = 'Not enough Bitcoins available.'
    respond_to do |format|
        format.html { redirect_to @wallet  }
        format.json { head :no_content }
      end
    
    
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wallet
      @wallet = Wallet.find(params[:id])
    end

    def create_output(amount, address)
      {value: amount, address: address}
    end

    def build_new_tx(key, inputs, outputs)
      new_tx = build_tx do |t|

        # add the input you picked out earlier
        inputs.each do |new_input|
          prev_tx =Bitcoin::P::Tx.from_json(new_input.owner_transaction.original_json)
          t.input do |i|
            i.prev_out prev_tx
            i.prev_out_index get_address_index(prev_tx.outputs, new_input.address.val)
            i.signature_key key
          end
        end

        outputs.each do |new_output|
          # add an output that sends some bitcoins to another address
          puts "New output #{new_output}, #{new_output[:value]}, #{new_output[:address]} #{key.addr}"
          t.output do |o|
            o.value new_output[:value] # 0.5 BTC in satoshis
            o.script {|s| s.recipient new_output[:address] }
          end
        end

      end

      new_tx
    end

    # Matches address to index in outputs
    def get_address_index(outputs, address)
      outputs.each_with_index {|out, index|
        if (out.parsed_script.get_addresses & [address]).any?
          # we found it
          return index
        end
      }
      return 0
    end

    def bin_to_hex(s)
      s.each_byte.map { |b| b.to_s(16).rjust(2,'0') }.join
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def wallet_params
      params.require(:wallet).permit(:public_key, :private_key, :name)
    end
end

app/helpers/wallets_helper.rb
module WalletsHelper
end

app/views/wallets/_form.html.erb
<%= form_for(@wallet) do |f| %>
  <% if @wallet.errors.any? %>
    <div class="alert alert-danger" role="alert">
      <h2><%= pluralize(@wallet.errors.count, "error") %> prohibited this wallet from being saved:</h2>

      <ul>
      <% @wallet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= label(:wallet, :name) %>
    <%= text_field(:wallet, :name, class: "form-control") %>
  </div>

  <div class="actions">
    <%= f.submit(class:"btn btn-primary btn-lg")%>
  </div>
<% end %>

app/views/wallets/_send_bitcoins.html.erb
<div class="jumbotron">
  <%= form_tag send_bitcoins_url(@wallet) do%>
    <h2>Send money</h2>
    <div class="form-group">
      <%= label_tag(:send_address, "Send To") %>
      <%= text_field_tag(:send_address, '', class: "form-control", placeholder: "Enter full Bitcoin Address", required: true) %>
    </div>
    <div class="form-group">
      <%= label(:amount, "Total amount") %> (BTC)
      <%= number_field_tag(:amount, '' , class: "form-control", placeholder: "Format 0.1", required: true, autocomplete: 'off', step: '0.00000001') %>
    </div>
    <div class="form-group">
      <%= label(:round, "Round amount") %><br />
      <input class="form-control" id="ex1" data-slider-id='ex1Slider' type="text" data-slider-min="1" data-slider-max="8" data-slider-step="1" data-slider-value="8" name="round" />
    </div>
    <div class="form-group">
      <span class='example'>No amount entered</span>
    </div>
    <div class="form-group">
      <%= label(:tx_fee, "TX Fee") %> (BTC)
      <%= text_field_tag(:tx_fee, '0.0001' , class: "form-control", placeholder: "Format 0.1") %>
    </div>
  

  <p><input type='submit' class="btn btn-primary btn-lg" role="button" value='Pay now' /></p>
  <%= hidden_field_tag(:rounded_amount, 0) %>
  <% end %>
</div>

app/views/wallets/edit.html.erb
<h1>Editing Wallet</h1>

<%= render 'form' %>

<%= link_to 'Show', @wallet %> |
<%= link_to 'Back', wallets_path %>

app/views/wallets/index.html.erb
<p id="notice"><%= notice %></p>

<div class="row">

  <h1>Listing Wallets</h1>
</div>
<div class="row">
  <div class="col-md-12">
    <table class='table'>
      <thead>
        <tr>
          <th>Name</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @wallets.each do |wallet| %>
          <tr class='table-striped'>
            <td><%= link_to wallet, wallet %></td>
            <td><%= link_to 'Show', wallet, class: "btn btn-primary" %></td>
            <td><%= link_to 'Edit', edit_wallet_path(wallet), class: "btn btn-info" %></td>
            <td><%= link_to 'Destroy', wallet, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<%= link_to 'New Wallet', new_wallet_path, class: "btn btn-success" %>

app/views/wallets/new.html.erb
<h1>New Wallet</h1>

<%= render 'form' %>

<%= link_to 'Back', wallets_path %>

app/views/wallets/show.html.erb
<% if notice %>
<div class="alert alert-success" role="alert"><%= notice %></div>
<% end %>
<% if flash[:error] %>
<div class="alert alert-danger" role="alert"><%= flash[:error] %></div>
<% end %>


<div class="row">
  <div class="col-md-12">
  	<h2><%= @wallet.name %></h2>
    <h3>Confirmed Total(<%= @wallet.get_confirmed_total%>) - Unconfirmed Total(<%= @wallet.get_unconfirmed_total%>)</h3>
  </div>
</div>
<%= render 'send_bitcoins' %>
<div class="row">
	<div class="col-md-12">
		<h3>Addresses<h3>
	</div>
</div>
<div class="row">
	<div class="col-md-6">
		<table class='table'>
      <thead>
        <tr>
          <th>Name</th>
          <th>Received</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody class='table-striped'>
        <% @wallet.addresses.each do |address| %>
          <tr class='table-striped'>
            <td><%= address %></td>
          </tr>
          <% address.outputs.each do |output| %>
          <tr >
            <td class='text-right'><%= output.value_mbtc %> <i>mBTC</i></td>
            <td><%= output.created_at %></td>
          </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<div class="row">

  <%= link_to 'Edit', edit_wallet_path(@wallet), class: "btn btn-info" %> |
  <%= link_to 'Back', wallets_path, class: "btn btn-default" %>
</div>
<script>


</script>
<style>
#ex1Slider .slider-selection {
  background: #BABABA;
}</style>